In [6]:
import pandas as pd
import numpy as np
import torch
import time 
from importlib import reload
import sliced
from sliced import base
from sliced.base import slice_y, grouped_sum, unique_counts
import scipy
from scipy import linalg
from scipy.linalg import eigh
from scipy.linalg import qr
import cir
from cir import CIR
reload(cir)
# import CIR_
# from CIR_ import CIR
# reload(CIR_)
# import CIR2_
# from CIR2_ import CIR2
# reload(CIR2_)

import sys
import numpy
# numpy.set_printoptions(suppress=True, threshold=sys.maxsize)
import math
from scipy.linalg import eigh
from scipy.linalg import eig
from numpy.linalg import norm
import torch
import geoopt
from geoopt.optim import RiemannianSGD
from geoopt.manifolds import Stiefel
from scipy.linalg import solve
from scipy.linalg import cholesky

In [18]:
from os.path import dirname, join as pjoin
import scipy.io as sio

# data_dir = pjoin(dirname(sio.__file__), 'matlab', 'tests', 'data')
data_dir = 'saveMatrix.mat'
mat_fname = pjoin(data_dir, 'saveMatrix.mat')
mat_contents = sio.loadmat(mat_fname)

fg = pd.read_csv('foregroundX.csv')
bg = pd.read_csv('backgroundX.csv')
Y = pd.read_csv('foregroundY.csv')
Yt = pd.read_csv('backgroundY.csv')

fg = fg.iloc[0:, 1:]
fg = np.array(fg)
bg = bg.iloc[0:, 1:]
bg = np.array(bg)

Y = Y.iloc[0:, 1:]
Y = np.array(Y)
Yt = Yt.iloc[0:, 1:]
Yt = np.array(Yt)


alpha = 0.0001
d = 2 

NotADirectoryError: [Errno 20] Not a directory: 'saveMatrix.mat/saveMatrix.mat'

In [198]:
A = [[0.9464,   0.7595,  0.6337], 
     [0.7595,   1.1467,   0.2953],
     [0.6337,   0.2953,   0.9921]]

B = [[0.5166,   0.4346,   0.3452],
     [0.4346,   0.9877,   0.3152],
     [0.3452,   0.3152,   0.2331]]

At = [[1.6385,    1.3992,    1.4475],
     [1.3992,    1.5247,    1.4521],
     [1.4475,    1.4521,    1.4314]]

Bt = [[0.3657,    0.5324,    0.7031],
     [0.5324,    0.8959,    1.0478],
     [0.7031,    1.0478,    1.3566]]

import scipy

v = np.eye(3)
v = v[:, 0:2]
alpha = 0.1



[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]]
[[-0.000000000000003552713678800501   0.0000000000000017763568394002505]
 [ 0.0000000000000002220446049250313 -0.0000000000000004440892098500626]
 [-4.013572012646964                  2.5027369882820736               ]]


In [47]:
G = [[1, 2], [2, 3], [2, 2]]
X = [[2, 1], [3, 1], [2, 2]]
# S = np.subtract(G, X)
# SS = np.sum(np.sum(np.multiply(S, S), axis=1), axis=0)
# XDiff = math.sqrt(SS *(1/3))

t = np.linalg.norm(np.transpose(X) @ X - np.eye(2), 'fro')
print(t)

# k = k/g
# X = X/L
# k = k @ np.linalg.inv(g)
# X @ np.linalg.inv(L)
# print(S)
# print(SS)
# print(XDiff)

21.047565179849187


In [202]:
import cir
from cir import CIR
reload(cir)

X = pd.read_csv('foregroundX.csv')
Xt = pd.read_csv('backgroundX.csv')
Y = pd.read_csv('foregroundY.csv')
Yt = pd.read_csv('backgroundY.csv')

X = X.iloc[:, 1:]
Xt = Xt.iloc[:, 1:]
Y = Y.iloc[:, 1:]
Yt = Yt.iloc[:, 1:]

# X =[[2, 1, 3],
#     [3, 4, 2],
#     [2, 2, 3],
#     [2, 1, 1]]

# Xt = [[1, 2, 1],
#       [2, 3, 1],
#       [2, 2, 4],
#       [2, 1, 1]]


# X = [[2.2332, 1.2224, 3.1789], 
#      [3.2215, 4.8862, 2.2209], 
#      [2.5542, 2.2218, 3.4516], 
#      [2.2988, 1.3772, 1.2099]]

# Xt = [[1.3887, 2.2234, 1.6542], 
#       [2.1528, 3.5823, 1.5512], 
#       [2.7998, 2.2653, 4.6982], 
#       [2.2341, 1.2871, 1.1273]]

# Y = [1, 2, 3, 2]
# Yt = [2, 1, 2, 3]

# alpha = 0.0001
alpha = 0.1
d = 2 

V = CIR(X, Y, Xt, Yt, alpha, d, "SGPM")
VVt = V @ V.T
numpy.set_printoptions(precision=15, threshold=sys.maxsize, suppress=True)

# matlab_02 = [[1.039790e-02, -1.256305e-02, -1.183676e-02, 2.401335e-02, -2.580892e-03, 5.512723e-03],
# [-1.256305e-02, 1.523789e-02, 1.485579e-02, -2.636259e-02, 3.224186e-03, -7.322264e-03],
# [-1.183676e-02, 1.485579e-02, 1.869630e-02, -2.360981e-03, 3.935469e-03, -1.250868e-02],
# [2.401335e-02, -2.636259e-02, -2.360981e-03, 1.749175e-01, -1.189587e-03, -1.708237e-02],
# [-2.580892e-03, 3.224186e-03, 3.935469e-03, -1.189587e-03, 8.311418e-04, -2.558988e-03],
# [5.512723e-03, -7.322264e-03, -1.250868e-02, -1.708237e-02, -2.558988e-03, 1.036333e-02],
# [9.290131e-03, -1.188047e-02, -1.675442e-02, -8.098502e-03, -3.486199e-03, 1.230109e-02],
# [-6.747845e-03, 8.229302e-03, 8.400917e-03, -1.214325e-02, 1.812304e-03, -4.436199e-03],
# [9.832186e-03, -1.190373e-02, -1.142061e-02, 2.161708e-02, -2.483998e-03, 5.484776e-03],
# [1.432085e-03, -1.692617e-03, -1.275363e-03, 5.004820e-03, -2.876693e-04, 3.356115e-04]]


# matlab_identity_11 = [[5.096635e-01, -8.973609e-02, -1.807473e-02, 4.751714e-02],
# [-1.754777e-02, -3.012023e-02, -8.973609e-02, 3.097544e-01],
# [2.758379e-02, -2.218888e-01, -8.460333e-04, 1.919806e-02],
# [-1.807473e-02, 2.758379e-02, 2.666579e-03, -1.940980e-02],
# [2.956133e-04, 2.221603e-03, 4.751714e-02, -2.218888e-01],
# [-1.940980e-02, 1.595284e-01, 1.222758e-03, -1.290108e-02]]

# matlab_toy_float = [[9.400524e-01, -2.279785e-01, -6.617897e-02],
# [-2.279785e-01, 1.330057e-01, -2.516763e-01],
# [-6.617897e-02, -2.516763e-01, 9.269419e-01]]
# VVt_s = VVt[:6, :4]
# norm = np.linalg.norm(VVt-matlab_toy_float, ord='fro')
# print("This is the norm of the difference")
# print(norm)
# print("this is the first 10 rows and first 6 columns of the output")
# print(VVt_s)
print("This is VV^t")
print(VVt)


This is A
[[ 0.248141580975918  0.938938984045707 -0.297830101537446]
 [ 0.938938984045706  3.552877902665641 -1.129138302197336]
 [-0.297830101537446 -1.129138302197336  0.472083676628535]]
------------------
This is B
[[ 0.353158829255701  1.329548989187601 -0.067198579899061]
 [ 1.329548989187601  5.005615806739783 -0.264348837587272]
 [-0.067198579899061 -0.264348837587272  0.611441227238094]]
------------------
This is At
[[ 0.19322701348527   0.023754675264259  0.816561776741293]
 [ 0.023754675264259  0.302475975463164  0.150436751271417]
 [ 0.816561776741293  0.150436751271417  3.459087084369962]]
------------------
This is Bt
[[ 0.300950682059123  0.014107019192699  1.108221637598413]
 [ 0.014107019192699  0.448557757038377  0.129529465697909]
 [ 1.108221637598413  0.129529465697909  4.337530572954972]]
------------------
This is initial V0
[[ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]]
------------------
This is G
[[-0.000000000900002  0.000000000241791]
 [-0.000000003613991  0.00000000096

In [66]:
def f(A, B, alpha, v, At, Bt):
    bv = np.linalg.inv(np.transpose(v) @ B @ v)
    va = np.transpose(v) @ A @ v
    bv_t = np.linalg.inv(np.transpose(v) @ Bt @ v)
    va_t = np.transpose(v) @ At @ v

    f_v = -np.matrix.trace(va @ bv) + alpha * np.matrix.trace(va_t @ bv_t)
    return f_v


def grad(A, B, alpha, v, At, Bt):
    bv = np.linalg.inv(np.transpose(v) @ B @ v)
    va = np.transpose(v) @ A @ v
    bv_t = np.linalg.inv(np.transpose(v) @ Bt @ v)
    va_t = np.transpose(v) @ At @ v

    gradient = -2 * (A @ v @ bv - B @ v @ bv @ va @ bv -
                     alpha * (At @ v @ bv_t - Bt @ v @ bv_t @ va_t @ bv_t))
    return gradient


def SGPM(X, A, B, At, Bt, a):
    X = np.array(X)
    n, k = X.shape

    xtol = 1e-20
    gtol = 1e-5
    ftol = 1e-20
    rho = 1e-4
    eta = 0.2
    gamma = 0.85
    tau = 1e-3
    STPEPS = 1e-10
    nt = 5
    mxitr = 3000
    alpha = 0.85
    record = 0
    projG = 1
    iscomplex = 0
    crit = np.ones((nt, 3))
    invH = True

    if k < n/2:
        invH = False
        eye2k = np.eye(2 * k)

    # Initial function value and gradient
    # Prepare for iterations
    F = f(A, B, a, X, At, Bt)

    G = grad(A, B, a, X, At, Bt)
    nfe = 1

    print("This is G")
    print(G)
    print("This is X")
    print(X)

    GX = np.transpose(G) @ X

    if invH:
        GXT = G @ np.transpose(X)
        H = (GXT - np.transpose(GXT))
    else:
        if projG == 1:
            U = np.hstack((G, X))
            V = np.hstack((X, -G))
            VU = np.transpose(V) @ U
        elif projG == 2:
            GB = G - 0.5 * X @ (np.transpose(X) @ G)
            U = np.hstack((GB, X))
            V = np.hstack((X, -GB))
            VU = np.transpose(V) @ U
        VX = np.transpose(V) @ X

    dtX = G - X @ GX
    nrmG = np.linalg.norm(dtX, ord='fro')
    Q = 1
    Cval = F

    if record == 1:
        fid = 1
        print(fid, '----------- Scaled Gradient Projection Method with Line search ----------- \n')
        print(fid, '%4s %8s %8s %10s %10s\n',
              'Iter', 'tau', 'F(X)', 'nrmG', 'XDiff')

    # main iteration
    F_eval = np.zeros((mxitr + 2, 1))
    Grad = np.zeros((mxitr + 2, 1))
    F_eval[0] = F
    Grad[0] = nrmG

    start_time = time.time()
    for itr in np.arange(1, mxitr+1).reshape(-1):
        XP = X
        FP = F
        dtXP = dtX
        nrmGP = nrmG

        # scale step size
        nls = 1
        deriv = rho * (nrmG**2)

        while True:
            # Update Scheme
            if invH:
                if abs(alpha) < rho:    # Explicit Euler (Steepest Descent)
                    X = XP - tau * dtXP
                elif abs(alpha - 0.5) < rho:  # Crank-Nicolson
                    X = solve(np.eye(n) + (tau * 0.5) * H, XP -
                              (0.5 * tau) * dtXP, lower=False)
                elif abs(alpha - 1) < rho:  # Implicit EuLer
                    X = solve(np.eye(n) + tau * H, XP, lower=False)
                else:  # Convex Combination
                    X = solve(np.eye(n) + (tau * alpha) * H, XP -
                              ((1 - alpha) * tau) * dtXP, lower=False)

                if abs(alpha - 0.5) > rho:
                    XtX = np.transpose(X) @ X
                    L = cholesky(XtX, lower=False)
                    X = X @ np.linalg.inv(L)

            else:
                aa = solve(eye2k + (alpha * tau) * VU, VX)
                X = XP - U @ (tau * aa)

                if abs(alpha - 0.5) > rho:
                    XtX = np.transpose(X) @ X
                    L = cholesky(XtX, lower=False)
                    X = X @ np.linalg.inv(L)

            # calculate G, F
            F = f(A, B, a, X, At, Bt)
            G = grad(A, B, a, X, At, Bt)
            nfe = nfe + 1

            if F <= Cval - tau * deriv or nls >= 5:
                break

            tau = eta * tau
            nls = nls + 1

        GX = np.transpose(G) @ X
        dtX = G - X @ GX
        nrmG = np.linalg.norm(dtX, ord='fro')

        F_eval[itr+1] = F
        Grad[itr+1] = nrmG

        # Adaptive scaling matrix strategy
        if nrmG < nrmGP:
            if nrmG >= 0.5 * nrmGP:
                alpha = max(min(alpha * 1.1, 1), 0)
        else:
            alpha = max(min(alpha * 0.9, 0), 0.5)

        # Computing the Riemannian Gradient
        if invH:
            if abs(alpha) > rho:
                GXT = G @ np.transpose(X)
                H = GXT - np.transpose(GXT)
        else:
            if projG == 1:
                U = np.hstack((G, X))
                V = np.hstack((X, -G))
                VU = np.transpose(V) @ U
            elif projG == 2:
                GB = G - X @ (0.5 * np.transpose(GX))
                U = np.hstack((GB, X))
                V = np.hstack((X, -GB))
                VU = np.transpose(V) @ U
            VX = np.transpose(V) @ X

        # Compute the Alternate ODH step-size
        S = X - XP
        SS = np.sum(np.sum(np.multiply(S, S), axis=1), axis=0)

        XDiff = math.sqrt(SS * (1/n))
        FDiff = abs(FP - F) / (abs(FP) + 1)

        Y = dtX - dtXP
        SY = abs(np.sum(np.sum(np.multiply(S, Y), axis=1), axis=0))

        if itr % 2 == 0:
            tau = SS / SY
        else:
            YY = np.sum(np.sum(np.multiply(Y, Y), axis=1), axis=0)
            tau = SY / YY

        tau = max(min(tau, 1e20), 1e-20)

        # Stopping Rules
        crit[itr % nt, :] = [nrmG, XDiff, FDiff]
        mcrit = np.mean(crit[max(0, itr-nt+1):itr, :], axis=0)

        if (XDiff < xtol and FDiff < ftol) or (nrmG < gtol) or np.all(mcrit[1:3] < 10 * np.array([xtol, ftol])):
            # if (XDiff < xtol and FDiff < ftol) or (nrmG < gtol) or all(mcrit[1:3] < 10 * np.hstack((xtol, ftol))):
            if itr <= 2:
                ftol = 0.1 * ftol
                xtol = 0.1 * xtol
                gtol = 0.1 * gtol
            else:
                msg = "converge"
                break

        Qp = Q
        Q = gamma * Qp + 1
        Cval = (gamma * Qp * Cval + F) / Q

    end_time = time.time()

    F_eval = F_eval[0:itr, 0]
    Grad = Grad[0:itr, 0]

    if itr >= mxitr:
        msg = "exceed max iteration"

    feasi = np.linalg.norm(np.transpose(X) @ X - np.eye(k), 'fro')

    if feasi > 1e-13:
        L = np.linalg.cholesky(X.T @ X)
        X = X @ np.linalg.inv(L)
        F = f(A, B, a, X, At, Bt)
        G = grad(A, B, a, X, At, Bt)
        dtX = G - X @ GX
        nrmG = np.linalg.norm(dtX, 'fro')
        feasi = np.linalg.norm(X.T @ X - np.eye(k), 'fro')

    print('---------------------------------------------------\n')
    print('Results for Scaled Gradient Projection Method \n')
    print('---------------------------------------------------\n')
    print('   Obj. function = %7.6e\n' % (-2*F))
    print('   Gradient norm = %7.6e \n' % nrmG)
    print('   ||X^T*X-I||_F = %3.2e\n' %
          np.linalg.norm(X.T @ X - np.eye(k), 'fro'))
    print('   Iteration number = %d\n' % itr)
    print('   Cpu time (secs) = %3.4f\n' % (end_time - start_time))
    print('   Number of evaluation(Obj. func) = %d\n' % nfe)
    return X

A = [[0.9464,   0.7595,  0.6337], 
     [0.7595,   1.1467,   0.2953],
     [0.6337,   0.2953,   0.9921]]

B = [[0.5166,   0.4346,   0.3452],
     [0.4346,   0.9877,   0.3152],
     [0.3452,   0.3152,   0.2331]]

C = [[1.6385,    1.3992,    1.4475],
     [1.3992,    1.5247,    1.4521],
     [1.4475,    1.4521,    1.4314]]

D = [[0.3657,    0.5324,    0.7031],
     [0.5324,    0.8959,    1.0478],
     [0.7031,    1.0478,    1.3566]]

# alpha = 0.0001
# d = 2 

# np.random.seed(0)
# v = np.random.rand(3, 2)
# v, r = np.linalg.qr(v)
v = np.eye(3)
v = v[:, 0:2]
print("This is initial V0")
print(v)

output = SGPM(v, A, B, C, D, 0.1)
VVt = output @ np.transpose(output)
print("This is VV^t")
print(VVt)

# Matlab_0 = [[3.982756e-01,    -2.914732e-01,  -3.933135e-01],
# [-2.914732e-01,  8.588114e-01,     -1.905197e-01],
# [-3.933135e-01,    -1.905197e-01,    7.429130e-01]]

# Matlab_1 = [[3.982768e-01, -2.914746e-01, -3.933128e-01],
# [-2.914746e-01, 8.588098e-01, -1.905206e-01],
# [-3.933128e-01, -1.905206e-01, 7.429135e-01]]
# norm = np.linalg.norm(Vt-Matlab_1, ord='fro')
# print("This is the norm of the difference")
# print(norm)

This is initial V0
[[1. 0.]
 [0. 1.]
 [0. 0.]]
This is G
[[-0.000000000000001  0.               ]
 [ 0.000000000000003 -0.000000000000001]
 [-4.013572012646961  2.502736988282074]]
This is X
[[1. 0.]
 [0. 1.]
 [0. 0.]]
---------------------------------------------------

Results for Scaled Gradient Projection Method 

---------------------------------------------------

   Obj. function = 8.126485e+02

   Gradient norm = 8.136984e-06 

   ||X^T*X-I||_F = 5.56e-16

   Iteration number = 63

   Cpu time (secs) = 1.1789

   Number of evaluation(Obj. func) = 83

This is VV^t
[[ 0.398275585989199 -0.29147324356918  -0.3933134778741  ]
 [-0.29147324356918   0.858811359920633 -0.190519700490965]
 [-0.3933134778741   -0.190519700490965  0.742913054090167]]


In [ ]:

        # if itr >= 50: 
        #     print("this is iteration ", itr)
        #     print("this is XP:")
        #     print(XP)
        #     print("                       ")
        #     print("this is FP")
        #     print(FP)
        #     print("                       ")
        #     print("this is dtXP")
        #     print(dtXP)
        #     print("                       ")
        #     print("this is alpha")
        #     print(alpha)
        #     print("                       ")
        #     print("this is rho")
        #     print(rho)
        #     print("                       ")
        #     print("this is tau")
        #     print(tau)
        #     print("                       ")
        #     print("this is L")
        #     print(L)
        #     print("                       ")
        #     print("this is Cval")
        #     print(Cval)
        #     print("                       ")
        #     # print("this is A")
        #     # print(A)
        #     # print("this is B")
        #     # print(B)
        #     # print("this is At")
        #     # print(At)
        #     # print("this is Bt")
        #     # print(Bt)
        #     print("this is nrmG")
        #     print(nrmG)
        #     print("                       ")
        #     print("this is nrmGP")
        #     print(nrmGP)
        #     print("                       ")
        #     print("this is GXT")
        #     print(GXT)
        #     print("                       ")
        #     print("this is H")
        #     print(H)
        #     print("                       ")
        #     # print("this is U")
        #     # print(U)
        #     # print("this is V")
        #     # print(V)
        #     # print("this is UV")
        #     # print(UV)
        #     # print("this is GB")
        #     # print(GB)
        #     print("this is S")
        #     print(S)
        #     print("                       ")
        #     print("this is SS")
        #     print(SS)
        #     print("                       ")
        #     print("this is XDiff")
        #     print(XDiff)
        #     print("                       ")
        #     print("this is FDiff")
        #     print(FDiff)
        #     print("                       ")
        #     print("this is Y")
        #     print(Y)
        #     print("                       ")
        #     print("this is SY")
        #     print(SY)
        #     print("                       ")
        #     print("this is YY")
        #     print(YY)
        #     print("------------------")

In [14]:
# import SyncRNG
# from SyncRNG import SyncRNG

# rnd = SyncRNG(seed = 16)
# v = np.zeros((6,6))

# for i in range(v.shape[0]):
#     for j in range(v.shape[1]):
#         v[j, i] = rnd.rand()

# print(v)

In [141]:
# from importlib import reload
import cir
from cir import CIR
reload(cir)
# import CIR_
# from CIR_ import CIR
# reload(CIR_)
import torch



t = CIR(X, Y, Xt, Yt, 0.0001, 2, "SGPM")
numpy.set_printoptions(suppress=True, threshold=sys.maxsize)
print(t)

O = pd.read_csv('output.csv')
O = pd.DataFrame(O)
O = O.iloc[:, 1:]
O = O.to_numpy()
output = O @ np.transpose(O)
output = torch.tensor(output)

# print(output)
torch.set_printoptions(threshold=sys.maxsize, sci_mode=False)
# print((torch.subtract(output, t)).detach().numpy())

# t1 = CIR2(X, Y, Xt, Yt, 0.0001, 2)
# print(np.subtract(output, t1))
# print(output)

/Users/lianama/anaconda3/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/lianama/anaconda3/lib/python3.10/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(


KeyboardInterrupt: 

In [117]:

# def CIR(X, Y, Xt, Yt, a, d, opt_option):
#     X = pd.DataFrame(X)
#     Xt = pd.DataFrame(Xt)
#     Y = pd.DataFrame(Y)
#     Yt = pd.DataFrame(Yt)

#     # n represents the rows of X. p represents the columns of X. m represent the rows of Xt.
#     n = len(X)
#     p = len(X.columns)
#     m = len(Xt)

#     if X.iloc[:, 0].equals(pd.Series(range(1, len(X) + 1))):
#         raise ValueError("X should not have an index column")

#     if Xt.iloc[:, 0].equals(pd.Series(range(1, len(Xt) + 1))):
#         raise ValueError("Xt should not have an index column")

#     if Y.iloc[:, 0].equals(pd.Series(range(1, len(Y) + 1))):
#         raise ValueError("Y should not have an index column")

#     if Yt.iloc[:, 0].equals(pd.Series(range(1, len(Yt) + 1))):
#         raise ValueError("Yt should not have an index column")

#     if len(Xt.columns) != p:
#         raise ValueError("Xt should have the same number of columns as X")

#     if len(Y) != n:
#         raise ValueError("Y must have the same number of rows as X")

#     if len(Yt) != m:
#         raise ValueError("Yt must have the same number of rows as Xt")

#     if not isinstance(d, int):
#         raise TypeError("d parameter must be an integer")

#     if d < 1:
#         raise ValueError("d must be greater than or equal to 1")

#     if a < 0:
#         raise ValueError("a must be greater than or equal to 0")

#     # Center the matrix X by subtracting the original matrix X by the column means of X
#     col_mean_x = X.mean(axis=0)
#     X = X - col_mean_x

#     # Calculate the Covariance Matrix
#     cov_matrix_X = X.cov()

#     # Define H
#     Y_unique_value = Y.nunique().item()
#     if Y_unique_value == 2:
#         H = 2
#     elif 2 < Y_unique_value <= 10:
#         H = Y_unique_value
#     else:
#         if d <= 2:
#             H = 10
#         else:
#             H = 4

#     # Define Ph, count the of ocurrence of y in each H interval.
#     interval_Ph = pd.cut(Y.iloc[:, 0], bins=H)
#     Ph = interval_Ph.value_counts().sort_index()

#     # Find the mean: Take each row of X and average among each interval separately
#     interval = np.linspace(np.min(Y), np.max(Y), num=H+1)
#     mh = []
#     for i in range(len(interval) - 1):
#         mask = (interval[i] <= Y) & (Y <= interval[i+1])
#         mask = mask.squeeze()  # convert to Series
#         x_rows_mean = np.mean(X[mask.values], axis=0)
#         mh.append(x_rows_mean)

#     mh = np.array(mh)

#     # Cov(E[X|Y])
#     sigma_X = np.zeros((X.shape[1], X.shape[1]))
#     for i in range(len(interval) - 1):
#         mask = (interval[i] <= Y) & (Y <= interval[i+1])
#         interval_mh = mh[i]
#         outer_product = np.outer(interval_mh, interval_mh)

#         if not np.isnan(outer_product).any():
#             sigma_X += outer_product

#     sigma_X = np.array(sigma_X)
#     eigenvalues, eigenvectors = np.linalg.eigh(sigma_X)
#     epsilon = 2 * abs(np.min(eigenvalues))
#     sigma_X = sigma_X + epsilon * np.identity(p)

#     cov_matrix_X = np.array(cov_matrix_X)

#     # Generalized Eigenvalue Decomposition
#     A = cov_matrix_X @ sigma_X @ cov_matrix_X
#     B = cov_matrix_X @ cov_matrix_X
#     eigenvalues, eigenvectors = eigh(cov_matrix_X, sigma_X)
#     # print(eigenvectors)

#     if a == 0:
#         v = eigenvectors[:, :d]
#         f_v = -1 * (np.trace(v.T @ A @ v @ np.linalg.inv(v.T @ B @ v)))
#         return v, f_v
#     # =================================================================
#     # Background data and the case when a > 0

#     # Center the data
#     col_means_xt = Xt.mean(axis=0)
#     Xt = Xt - col_means_xt

#     # Covariance Matrix
#     cov_matrix_Xt = Xt.cov()

#     # Define Ht
#     Yt_unique_value = Yt.nunique().item()
#     if Yt_unique_value == 2:
#         Ht = 2
#     elif 2 < Yt_unique_value <= 10:
#         Ht = Yt_unique_value
#     else:
#         if d <= 2:
#             Ht = 10
#         else:
#             Ht = 4

#     # Define Ph_t
#     interval_Ph_t = pd.cut(Yt.iloc[:, 0], bins=Ht)
#     Ph_t = interval_Ph_t.value_counts().sort_index()

#     # Find the mean: Take each row of X and average among each interval separately
#     interval_t = np.linspace(np.min(Yt), np.max(Yt), num=Ht+1)
#     mh_t = []
#     for i in range(len(interval_t) - 1):
#         mask_t = (interval_t[i] <= Yt) & (Yt <= interval_t[i+1])
#         mask = mask.squeeze()
#         xt_rows_mean = np.mean(Xt[mask_t.values], axis=0)
#         mh_t.append(xt_rows_mean)

#     mh_t = np.array(mh_t)

#     # Cov(E[Xt|Yt])
#     sigma_Xt = np.zeros((Xt.shape[1], Xt.shape[1]))
#     for i in range(len(interval_t) - 1):
#         mask_t = (interval_t[i] <= Yt) & (Yt <= interval_t[i+1])
#         interval_mh_t = mh_t[i]
#         outer_product_t = np.outer(interval_mh_t, interval_mh_t)

#         if not np.isnan(outer_product_t).any():
#             sigma_Xt += outer_product_t

#     sigma_Xt = np.array(sigma_Xt)
#     eigenvalues_t, eigenvectors_t = np.linalg.eigh(sigma_Xt)
#     epsilon_t = 2 * abs(np.min(eigenvalues_t))
#     sigma_Xt = sigma_Xt + epsilon_t * np.identity(p)

#     cov_matrix_Xt = np.array(cov_matrix_Xt)

#     # Generalized Eigenvalue Decomposition
#     At = cov_matrix_Xt @ sigma_Xt @ cov_matrix_Xt
#     Bt = cov_matrix_Xt @ cov_matrix_Xt

#     # Optimization on Manifold
#     if opt_option == "geoopt":
#         A = torch.tensor(A, dtype=torch.double)
#         B = torch.tensor(B, dtype=torch.double)
#         a = torch.tensor(a, dtype=torch.double)
#         At = torch.tensor(At, dtype=torch.double)
#         Bt = torch.tensor(Bt, dtype=torch.double)

#         stiefel = geoopt.manifolds.Stiefel()
#         torch.manual_seed(1)
#         initial_point = torch.randn(p, d)
#         initial_point, _ = torch.linalg.qr(initial_point)

#         v = geoopt.ManifoldParameter(initial_point, manifold=stiefel)

#         optimizer = RiemannianSGD([v], lr=1e-3, momentum=0.9)
#         max_iterations = 10000

#         for step in range(max_iterations):
#             vt = v.clone()
#             optimizer.zero_grad()
#             cost = f_geoopt(A, B, a, v, At, Bt)
#             gradient = grad_geoopt(A, B, a, v, At, Bt).to(torch.float)
#             v.grad = gradient
#             optimizer.step()
#             vt_plus = v.clone()

#             if stepExit(vt_plus, vt, cost, A, B, At, Bt, a):
#                 break

#         output = v @ v.t()
#         return output

#     if opt_option == "SGPM":
#         np.random.seed(2)
#         v = np.random.rand(p, d)
#         v, r = np.linalg.qr(v)

#         output = SGPM(v, A, B, At, Bt, a)
#         # return output
#         return output @ np.transpose(output)


# def f_geoopt(A, B, a, v, At, Bt):
#     v = v.data
#     v = v.to(torch.double)

#     bv_inv = torch.inverse(v.t() @ B @ v)
#     va = v.t() @ A @ v
#     bv_t_inv = torch.inverse(v.t() @ Bt @ v)
#     va_t = v.t() @ At @ v

#     f_v = -torch.trace(va @ bv_inv) + a * torch.trace(va_t @ bv_t_inv)
#     return f_v


# def grad_geoopt(A, B, a, v, At, Bt):
#     v = v.data
#     v = v.to(torch.double)

#     bv_inv = torch.inverse(v.t() @ B @ v)
#     va = v.t() @ A @ v
#     bv_t_inv = torch.inverse(v.t() @ Bt @ v)
#     va_t = v.t() @ At @ v

#     avb = A @ v @ bv_inv - B @ v @ bv_inv @ va @ bv_inv
#     avb_t = At @ v @ bv_t_inv - Bt @ v @ bv_t_inv @ va_t @ bv_t_inv

#     gradient = -2 * (avb - a * avb_t)
#     return gradient


# def stepExit(vt_plus, vt, cost, A, B, At, Bt, a) -> bool:
#     xtol = 1e-6
#     gtol = 1e-4
#     ftol = 1e-12
#     distance = torch.norm(vt_plus @ vt_plus.t() - vt @ vt.t(), 'fro')
#     vt_plus_gradient = grad_geoopt(A, B, a, vt_plus, At, Bt)
#     cost_vt_plus = f_geoopt(A, B, a, vt_plus, At, Bt)

#     if distance < xtol:
#         return True
#     elif torch.norm(vt_plus_gradient, 'fro') < gtol:
#         return True
#     elif abs(cost_vt_plus - cost) < ftol:
#         return True
#     else:
#         return False


# def f(A, B, a, v, At, Bt):
#     bv_inv = np.linalg.inv(np.transpose(v) @ B @ v)
#     va = np.transpose(v) @ A @ v
#     bv_t_inv = np.linalg.inv(np.transpose(v) @ Bt @ v)
#     va_t = np.transpose(v) @ At @ v
#     f_v = -np.matrix.trace(va @ bv_inv) + a * np.matrix.trace(va_t @ bv_t_inv)
#     return f_v


# def grad(A, B, a, v, At, Bt):
#     bv_inv = np.linalg.inv(np.transpose(v) @ B @ v)
#     va = np.transpose(v) @ A @ v
#     bv_t_inv = np.linalg.inv(np.transpose(v) @ Bt @ v)
#     va_t = np.transpose(v) @ At @ v

#     avb = A @ v @ bv_inv - B @ v @ bv_inv @ va @ bv_inv
#     avb_t = At @ v @ bv_t_inv - Bt @ v @ bv_t_inv @ va_t @ bv_t_inv

#     gradient = -2 * (avb - a * avb_t)
#     return gradient


# def SGPM(X, A, B, At, Bt, a):
#     X = np.array(X)
#     n, k = X.shape

#     xtol = 1e-6
#     gtol = 1e-4
#     ftol = 1e-12
#     rho = 1e-4
#     eta = 0.1
#     gamma = 0.85
#     tau = 1e-3
#     STPEPS = 1e-10
#     nt = 5
#     mxitr = 1000
#     alpha = 0.85
#     record = 0
#     projG = 1
#     iscomplex = 0
#     crit = np.ones((nt, 3))
#     invH = True

#     if k < n/2:
#         invH = False
#         eye2k = np.identity(2 * k)

#     # Initial function value and gradient
#     # Prepare for iterations
#     F = f(A, B, a, X, At, Bt)
#     G = grad(A, B, a, X, At, Bt)

#     GX = np.transpose(G) @ X

#     if invH:
#         GXT = G @ np.transpose(X)
#         H = (GXT - np.transpose(GXT))
#     else:
#         if projG == 1:
#             U = np.hstack((G, X))
#             V = np.hstack((X, -G))
#             VU = np.transpose(V) @ U
#         elif projG == 2:
#             GB = G - 0.5 * X @ (np.transpose(X) @ G)
#             U = np.hstack((GB, X))
#             V = np.hstack((X, -GB))
#             VU = np.transpose(V) @ U
#         VX = np.transpose(V) @ X

#     dtX = G - X @ GX
#     nrmG = np.linalg.norm(dtX, ord='fro')
#     Q = 1
#     Cval = F

#     # main iteration
#     F_eval = np.zeros((mxitr + 1, 1))
#     Grad = np.zeros((mxitr + 1, 1))
#     F_eval[0] = F
#     Grad[0] = nrmG
#     for itr in np.arange(1,mxitr+1).reshape(-1):
#         # for itr in range(0, mxitr):
#         XP = X
#         FP = F
#         dtXP = dtX
#         nrmGP = nrmG

#         # scale step size
#         nls = 1
#         deriv = rho * (nrmG**2)

#         while True:
#             # Update Scheme
#             if invH:
#                 if abs(alpha) < rho:    # Explicit Euler (Steepest Descent)
#                     X = XP - tau * dtXP
#                 elif abs(alpha - 0.5) < rho:  # Crank-Nicolson
#                     X = solve(np.eye(n) + (tau * 0.5) * H, XP - (0.5 * tau) * dtXP)
#                 elif abs(alpha - 1) < rho:  # Implicit EuLer
#                     X = solve(np.eye(n) + tau * H, XP)
#                 else:  # Convex Combination
#                     X = solve(np.eye(n) + (tau * alpha) * H, XP - ((1 - alpha) * tau) * dtXP)

#                 if abs(alpha - 0.5) > rho:
#                     XtX = np.transpose(X) @ X
#                     L = cholesky(XtX, lower=False)
#                     X = X/ L
#                     # X = X @ np.linalg.inv(L)

#             else:
#                 aa = solve(eye2k + (alpha * tau) * VU, VX)
#                 X = XP - U @ (tau * aa)

#                 if abs(alpha - 0.5) > rho:
#                     XtX = np.transpose(X) @ X
#                     L = cholesky(XtX, lower=False)
#                     # X = X @ np.linalg.inv(L)
#                     X = X / L

#             # calculate G, F
#             F = f(A, B, a, X, At, Bt)
#             G = grad(A, B, a, X, At, Bt)

#             if F <= Cval - tau * deriv or nls >= 5:
#                 break

#             tau = eta * tau
#             nls = nls + 1

#         GX = np.transpose(G) @ X
#         dtX = G - X @ GX
#         nrmG = np.linalg.norm(dtX, ord='fro')

#         F_eval[itr+1] = F
#         # print(Grad)
#         Grad[itr+1] = nrmG

#         # Adaptive scaling matrix strategy
#         if nrmG < nrmGP:
#             if nrmG >= 0.5 * nrmGP:
#                 alpha = max(min(alpha * 1.1, 1), 0)
#         else:
#             alpha = max(min(alpha * 0.9, 0), 0.5)

#         # Computing the Riemannian Gradient
#         if invH:
#             if abs(alpha) > rho:
#                 GXT = G @ np.transpose(X)
#                 H = GXT - np.transpose(GXT)
#         else:
#             if projG == 1:
#                 U = np.hstack((G, X))
#                 V = np.hstack((X, -G))
#                 VU = np.transpose(V) @ U
#             elif projG == 2:
#                 GB = G - X @ (0.5 * np.transpose(GX))
#                 U = np.hstack((GB, X))
#                 V = np.hstack((X, -GB))
#                 VU = np.transpose(V) @ U
#             VX = np.transpose(V) @ X

#         # Compute the Alternate ODH step-size
#         S = X - XP
#         SS = sum(sum(np.multiply(S,S)))
#         # SS = np.sum(np.sum(np.multiply(S, S), axis=1), axis=0)

#         XDiff = math.sqrt(SS / n)
#         FDiff = abs(FP - F) / (abs(FP) + 1)

#         Y = dtX - dtXP
#         SY = np.abs(sum(sum(np.multiply(S,Y))))
#         # SY = abs(np.sum(np.sum(np.multiply(S, Y), axis=1), axis=0))

#         if np.mod(itr, 2) == 0:
#             # if itr % 2 == 0:
#             tau = SS / SY
#         else:
#             YY = sum(sum(np.multiply(Y,Y)))
#             # YY = np.sum(np.sum(np.multiply(Y, Y), axis=1), axis=0)
#             tau = SY / YY

#         tau = max(min(tau, 1e+20), 1e-20)

#         # Stopping Rules
#         crit[itr, :] = np.array([nrmG, XDiff, FDiff])
#         mcrit = mean(crit[np.arange(itr - np.amin(nt,itr) + 1,itr+1),:],1)
#         # mcrit = np.mean(crit[max(0, itr-nt+1):itr, :], axis=0)

#         if (XDiff < xtol and FDiff < ftol) or nrmG < gtol or all(mcrit[1:3] < 10 * np.hstack((xtol, ftol))):
#             if itr <= 2:
#                 ftol = 0.1 * ftol
#                 xtol = 0.1 * xtol
#                 gtol = 0.1 * gtol
#             else:
#                 msg = "converge"
#                 break

#         Qp = Q
#         Q = gamma * Qp + 1
#         Cval = (gamma * Qp * Cval + F) / Q

#     F_eval = F_eval[0:itr, 0]
#     Grad = Grad[0:itr, 0]

#     if itr >= mxitr:
#         msg = "exceed max iteration"

#     feasi = np.linalg.norm(np.transpose(X) @ X - np.eye(k), 'fro')

#     if feasi > 1e-13:
#         L = np.linalg.cholesky(X.T @ X)
#         X = X @ np.linalg.inv(L)
#         F = f(A, B, a, X, At, Bt)
#         G = grad(A, B, a, X, At, Bt)
#         dtX = G - X @ GX
#         nrmG = np.linalg.norm(dtX, 'fro')
#         feasi = np.linalg.norm(X.T @ X - np.eye(k), 'fro')

#     feasi = np.linalg.norm(X.T @ X - np.eye(k), 'fro')
#     print("This is objective function: ", F)
#     return X



# X = pd.read_csv('foregroundX.csv')
# Y = pd.read_csv('foregroundY.csv')
# Xt = pd.read_csv('backgroundX.csv')
# Yt = pd.read_csv('backgroundY.csv')

# X = X.iloc[:, 1:]
# Xt = Xt.iloc[:, 1:]
# Y = Y.iloc[:, 1:]
# Yt = Yt.iloc[:, 1:]

# t = CIR(X, Y, Xt, Yt, 0.0001, 2, "SGPM")
# numpy.set_printoptions(suppress=True, threshold=sys.maxsize)
# print(t)


KeyboardInterrupt



In [15]:
# X = pd.read_csv('foregroundX.csv')
# Y = pd.read_csv('foregroundY.csv')
# Xt = pd.read_csv('backgroundX.csv')
# Yt = pd.read_csv('backgroundY.csv')

# X = X.iloc[:, 1:]
# Xt = Xt.iloc[:, 1:]
# Y = Y.iloc[:, 1:]
# Yt = Yt.iloc[:, 1:]

# cov_X = X.cov()
# cov_Xt = Xt.cov()

# Y_unique_value = Y.nunique().item()
# Yt_unique_value = Yt.nunique().item()
# H = 8
# Ht = 2
# unique_y_vals, counts = unique_counts(Y)
# cumsum_y = np.cumsum(counts)
# n_y_values = unique_y_vals.shape[0]
# slice_partition = np.hstack((0, cumsum_y))

# slice_indicator = np.ones(Y.shape[0], dtype=int)
# for j, (start_idx, end_idx) in enumerate(zip(slice_partition, slice_partition[1:])): 
#     if j == len(slice_partition) - 2:
#         slice_indicator[start_idx:] = j
#     else:
#         slice_indicator[start_idx:end_idx] = j

# slice_counts = np.bincount(slice_indicator)
# n, p = X.shape
# Q, R = linalg.qr(X, mode='economic')
# inv_idx = np.concatenate(([0], np.diff(slice_indicator).nonzero()[0] + 1))
# Z_means = np.add.reduceat(Q, inv_idx) / np.sqrt(slice_counts.reshape(-1, 1))
# M = np.dot(Z_means.T, Z_means)

# cov_X = np.array(cov_X)

# A = cov_X @ M @ cov_X
# B = cov_X @ cov_X
# """-----------background------------"""
# unique_yb_vals, countsB = unique_counts(Yt)
# cumsum_yb = np.cumsum(countsB)
# n_yb_values = unique_yb_vals.shape[0]
# slice_partition_B = np.hstack((0, cumsum_yb))

# slice_indicatorB = np.ones(Yt.shape[0], dtype=int)
# for j, (start_idx, end_idx) in enumerate(zip(slice_partition_B, slice_partition_B[1:])): 
#     if j == len(slice_partition_B) - 2:
#         slice_indicatorB[start_idx:] = j
#     else:
#         slice_indicatorB[start_idx:end_idx] = j

# slice_counts_B = np.bincount(slice_indicatorB)
# m, k = Xt.shape
# Qt, Rt = linalg.qr(Xt, mode='economic')
# inv_idx_B = np.concatenate(([0], np.diff(slice_indicatorB).nonzero()[0] + 1))
# Z_means_B = np.add.reduceat(Qt, inv_idx_B) / np.sqrt(slice_counts_B.reshape(-1, 1))
# Mt = np.dot(Z_means_B.T, Z_means_B)

# cov_Xt = np.array(cov_Xt)

# At = cov_Xt @ Mt @ cov_Xt
# Bt = cov_Xt @ cov_Xt


# def f(A, B, a, v, At, Bt):
#     bv_inv = np.linalg.inv(np.transpose(v) @ B @ v)
#     va = np.transpose(v) @ A @ v
#     bv_t_inv = np.linalg.inv(np.transpose(v) @ Bt @ v)
#     va_t = np.transpose(v) @ At @ v
#     f_v = -np.matrix.trace(va @ bv_inv) + a * np.matrix.trace(va_t @ bv_t_inv)
#     return f_v


# def grad(A, B, a, v, At, Bt):
#     bv_inv = np.linalg.inv(np.transpose(v) @ B @ v)
#     va = np.transpose(v) @ A @ v
#     bv_t_inv = np.linalg.inv(np.transpose(v) @ Bt @ v)
#     va_t = np.transpose(v) @ At @ v

#     avb = A @ v @ bv_inv - B @ v @ bv_inv @ va @ bv_inv
#     avb_t = At @ v @ bv_t_inv - Bt @ v @ bv_t_inv @ va_t @ bv_t_inv

#     gradient = -2 * (avb - a * avb_t)
#     return gradient

# def SGPM(X, A, B, At, Bt, a):
#     X = np.array(X)
#     n, k = X.shape

#     xtol = 1e-6
#     gtol = 1e-4
#     ftol = 1e-12
#     rho = 1e-4
#     eta = 0.1
#     gamma = 0.85
#     tau = 1e-3
#     STPEPS = 1e-10
#     nt = 5
#     mxitr = 1000
#     alpha = 0.85
#     record = 0
#     projG = 2
#     iscomplex = 0
#     crit = np.ones((mxitr, 3))
#     invH = True

#     if k < n/2:
#         invH = False
#         eye2k = np.identity(2 * k)

#     # Initial function value and gradient
#     # Prepare for iterations
#     F = f(A, B, a, X, At, Bt)
#     G = grad(A, B, a, X, At, Bt)

#     GX = np.transpose(G) @ X

#     if invH:
#         GXT = G @ np.transpose(X)
#         H = GXT - np.transpose(GXT)
#     else:
#         if projG == 1:
#             U = np.hstack((G, X))
#             V = np.hstack((X, -G))
#             VU = np.transpose(V) @ U
#         elif projG == 2:
#             GB = G - 0.5 * X @ (np.transpose(X) @ G)
#             U = np.hstack((GB, X))
#             V = np.hstack((X, -GB))
#             VU = np.transpose(V) @ U
#         VX = np.transpose(V) @ X

#     dtX = G - X @ GX
#     nrmG = np.linalg.norm(dtX, ord='fro')
#     Q = 1
#     Cval = F

#     # main iteration
#     F_eval = np.zeros((mxitr + 1, 1))
#     Grad = np.zeros((mxitr + 1, 1))
#     F_eval[0] = F
#     Grad[0] = nrmG
#     for itr in range(0, mxitr):
#         XP, FP, dtXP, nrmGP = X, F, dtX, nrmG

#         # scale step size
#         nls = 1
#         deriv = rho * (nrmG**2)

#         while True:
#             # Update Scheme
#             if invH:
#                 if abs(alpha) < rho:    # Explicit Euler (Steepest Descent)
#                     X = XP - tau * dtXP
#                 elif abs(alpha - 0.5) < rho:  # Crank-Nicolson
#                     A = np.eye(n) + (tau * 0.5) * H
#                     X = solve(
#                         A, XP - (0.5 * tau) * dtXP, lower=False)
#                 elif abs(alpha - 1) < rho:  # Implicit EuLer
#                     A = np.eye(n) + tau * H
#                     X = solve(A, XP, lower=False)
#                 else:  # Convex Combination
#                     A = np.eye(n) + (tau * alpha) * H
#                     X = solve(
#                         A, XP - ((1 - alpha) * tau) * dtXP, lower=False)

#                 if abs(alpha - 0.5) > rho:
#                     XtX = np.transpose(X) @ X
#                     L = cholesky(XtX, lower=False)
#                     X = X @ np.linalg.inv(L)

#             else:
#                 aa = solve(eye2k + (alpha * tau) * VU, VX)
#                 X = XP - U @ (tau * aa)

#                 if abs(alpha - 0.5) > rho:
#                     XtX = np.transpose(X) @ X
#                     L = cholesky(XtX, lower=False)
#                     X = X @ np.linalg.inv(L)

#             # calculate G, F
#             F = f(A, B, a, X, At, Bt)
#             G = grad(A, B, a, X, At, Bt)

#             if F <= Cval - tau * deriv or nls >= 5:
#                 break

#             tau = eta * tau
#             nls += 1

#         GX = np.transpose(G) @ X
#         dtX = G - X @ GX
#         nrmG = np.linalg.norm(dtX, ord='fro')

#         F_eval[itr+1] = F
#         # print(Grad)
#         Grad[itr+1] = nrmG

#         # Adaptive scaling matrix strategy
#         if nrmG < nrmGP:
#             if nrmG >= 0.5 * nrmGP:
#                 alpha = max(min(alpha * 1.1, 1), 0)
#         else:
#             alpha = max(min(alpha * 0.9, 0), 0.5)

#         # Computing the Riemannian Gradient
#         if invH:
#             if abs(alpha) > rho:
#                 GXT = G @ np.transpose(X)
#                 H = GXT - np.transpose(GXT)
#         else:
#             if projG == 1:
#                 U = np.hstack((G, X))
#                 V = np.hstack((X, -G))
#                 VU = np.transpose(V) @ U
#             elif projG == 2:
#                 GB = G - X @ (0.5 * np.transpose(GX))
#                 U = np.hstack((GB, X))
#                 V = np.hstack((X, -GB))
#                 VU = np.transpose(V) @ U
#             VX = np.transpose(V) @ X

#         # Compute the Alternate ODH step-size
#         S = X - XP
#         SS = np.sum(np.sum(np.multiply(S, S), axis=1), axis=0)

#         XDiff = math.sqrt(SS / n)
#         FDiff = abs(FP - F) / (abs(FP) + 1)

#         Y = dtX - dtXP
#         SY = abs(np.sum(np.sum(np.multiply(S, Y), axis=1), axis=0))

#         if itr % 2 == 0:
#             tau = SS / SY
#         else:
#             YY = np.sum(np.sum(np.multiply(Y, Y), axis=1), axis=0)
#             tau = SY / YY

#         tau = max(min(tau, 1e20), 1e-20)

#         # Stopping Rules
#         crit[itr, :] = [nrmG, XDiff, FDiff]

#         mcrit = np.mean(crit[max(0, itr-nt+1):itr, :], axis=0)
#         # mcrit = np.mean(crit[itr - min(nt, itr) + 1:itr, :], axis=0)
#         # print("Iteration:", itr)
#         # print("size of crit", crit.shape)
#         # print("size of mcrit", mcrit.shape)

#         if (XDiff < xtol and FDiff < ftol) or nrmG < gtol or all(mcrit[1:3] < 10 * np.hstack((xtol, ftol))):
#             if itr <= 2:
#                 ftol = 0.1 * ftol
#                 xtol = 0.1 * xtol
#                 gtol = 0.1 * gtol
#             else:
#                 msg = "converge"
#                 break

#         Qp = Q
#         Q = gamma * Qp + 1
#         Cval = (gamma * Qp * Cval + F) / Q

#     F_eval = F_eval[0:itr, 0]
#     Grad = Grad[0:itr, 0]

#     if itr >= mxitr:
#         msg = "exceed max iteration"

#     feasi = np.linalg.norm(np.transpose(X) @ X - np.eye(k), 'fro')

#     if feasi > 1e-13:
#         L = np.linalg.cholesky(X.T @ X)
#         X = X @ np.linalg.inv(L)
#         F = f(A, B, a, X, At, Bt)
#         G = grad(A, B, a, X, At, Bt)
#         dtX = G - X @ GX
#         nrmG = np.linalg.norm(dtX, 'fro')
#         feasi = np.linalg.norm(X.T @ X - np.eye(k), 'fro')

#     feasi = np.linalg.norm(X.T @ X - np.eye(k), 'fro')
#     return X

# np.random.seed(2)
# v = np.random.rand(p, 2)
# v, r = np.linalg.qr(v)

# output = SGPM(v, A, B, At, Bt, 0.0001)
#         # return output
# numpy.set_printoptions(suppress=True, threshold=sys.maxsize)
# print(output @ np.transpose(output))


In [16]:
# interval_Ph = pd.cut(Y.iloc[:, 0], bins=H)
# Ph = interval_Ph.value_counts().sort_index()
# interval = np.linspace(np.min(Y), np.max(Y), num=H+1)
# mh = []
# for i in range(len(interval) - 1):
#     mask = (interval[i] <= Y) & (Y <= interval[i+1])
#     mask = mask.squeeze()  # convert to Series
#     x_rows_mean = np.mean(X[mask.values], axis=0)
#     mh.append(x_rows_mean)

# # mh = np.array(mh)
# # print(mh)

# n_obs = np.floor(Y.shape[0]/H)
# n_samples_seen = 0 
# slice_partition = [0]

# while n_samples_seen < Y.shape[0] - 2: 
#     slice_start = np.where(cumsum_y >= n_samples_seen + n_obs)[0]
#     if slice_start.shape[0] == 0:
#         slice_start = cumsum_y.shape[0] - 1
#     else: 
#         slice_start = slice_start[0]

#     n_samples_seen = cumsum_y[slice_start]
#     slice_partition.append(n_samples_seen)
#     print(n_samples_seen)

# Z = np.sqrt(n) * Q
# Z = Q[np.argsort(Y), :]

# M = np.outer(Z_means, Z_means)
# M = np.dot(Z_means.T, Z_means)
# print(M)

# sigma_X = np.zeros((X.shape[1], X.shape[1]))
# for i in range(len(interval) - 1):
#     mask = (interval[i] <= Y) & (Y <= interval[i+1])
#     interval_mh = mh[i]
#     outer_product = np.outer(interval_mh, interval_mh)

#     if not np.isnan(outer_product).any():
#         sigma_X += outer_product
# print(sigma_X)
# M = np.dot(Z_means.T, Z_means) / n              # covariance matrix 
# print(M)

# print(M.shape)
# A = cov_X @ M @ cov_X
# B = M @ M
# eigenvalues, eigenvectors = eigh(cov_X, M)
# v = eigenvectors[:, :2]
# f_v = -1 * (np.trace(v.T @ A @ v @ np.linalg.inv(v.T @ B @ v)))

In [18]:
# import CIR_
# from CIR_ import CIR
# O = pd.read_csv('output.csv')
# O = pd.DataFrame(O)
# O = O.iloc[:, 1:]
# O = O.to_numpy()
# output = O @ np.transpose(O)

# output = torch.from_numpy(output)
# t = CIR(X, Y, Xt, Yt, 0.0001, 2, "SGPM")
# torch.set_printoptions(sci_mode=False)
# print(t)

# # print(torch.subtract(output, t))

# # t1 = CIR2(X, Y, Xt, Yt, 0.0001, 2)
# # print(np.subtract(output, t1))
# # print(output)

In [6]:
# t = pd.read_csv('test-fX.csv')
# t = pd.DataFrame(t)
# if t.iloc[:, 0].dtypes != t.iloc[:, 1].dtypes:
#     t = t.iloc[:, 1:]

In [ ]:
# t = CIR(X, Y, Xt, Yt, 0.0001, 2)
# print(torch.subtract(output, t))

# output = torch.from_numpy(output)
# print("Correct output....")
# print(output)

# # n = pd.read_csv('test - noIndex.csv')

# X = pd.read_csv('test - fX.csv')
# Y = pd.read_csv('test - fY.csv')
# Xt = pd.read_csv('test - bX.csv')
# Yt = pd.read_csv('test - fY.csv')